import functools
import logging
import psutil
import signal

from tqdm import tqdm
from angr.storage.memory_mixins import DefaultMemory
import angr

from .helpers import pc_offset
from .models import ConsolidatedBasicBlock, MultiStatesBasicBlock, BasicBlock, Color
from .exception import TaintedAddressMemoryWrite
from .tainting import (
    status_from_expression,
    build_expression_for_status,
    get_over_approximation_of_statuses,
)
from ..common import SourceCodeFilesManager
from ..config import TargetConfigManager, CommonConfig
from ..exception import AnalysisInterruptError, AnalysisInterruptKind
from ..log import LOGGER_NAME


logger = logging.getLogger(LOGGER_NAME)
logger.propagate = False

class Timeout(Exception):
    pass

def handler(signum, frame):
    raise Timeout()

signal.signal(signal.SIGALRM, handler)

def propagate_taint_on_cfg(
    initial_program_state: angr.SimState, block_consolidation_threshold: int
) -> dict[tuple[int], BasicBlock]:
    """
    Systematically discovers the control-flow-graph of the target program, and propagates the tainting across it.

    Starting from `initial_program_state`, this function systematically discovers reachable basic blocks of the program,
    by iteratively exploring the successor blocks of previously discovered blocks.

    At the same time, it propagates the tainting on the control-flow-graph, until a fixed-point is reached. This can be seen as a
    data-flow analysis https://en.wikipedia.org/wiki/Data-flow_analysis.

    The result is a collection of basic blocks, and, for each of them, a collection of possible tainting states at the beginning
    of the block. A tainting state maps each byte of the memory and registers to a status. A status can be one of :
    - The red taint, which means that this memory/register byte is influenced by the secret in all possible traversals of the
    control-flow-graph
    - The orange taint, which means that this memory/register byte is influenced by the secret in some possible traversals of
    the control-flow-graph but not all
    - The green taint, which means that this memory/register byte has an unknown value and is not influenced by the secret in any
    possible traversal of the control-flow-graph
    - A concrete value, which means that this memory/register byte is not influenced by the secret in any possible
    traversal of the control-flow-graph, and that it is guaranteed to have this concrete value.

    Each basic block is identified by a unique ID. The ID is determined by the call stack of the target program when this basic
    block was reached and the address of the first instruction of the basic block. Two basic blocks that correspond to the same
    program point but that were reached through a difference sequence of calls are considered different. This allows to analyze
    separately different calls of the same function.

    The output is a dict of discovered basic blocks, keyed by block IDs. An ID is a tuple of ints. A basic block stores one or
    several angr program states about to execute the first instruction of the basic block, and with symbolic values stored in its
    memory and registers that correspond to the tainting state.
    """

    # We configure the initial program state such that memory reads with a tainted address produce an orange tainted value.
    # This is required for the soundness of the analysis, as we have no information on the real location targeted by these
    # memory address, and thus they may read a memory region that contains secret data.
    contaminate_tainted_memory_reads_with_taint(initial_program_state)
    # We configure the initial program state such that an exception is raised if a memory write with a tainted address is
    # encountered. This is required for the soundness of the analysis, as we have no information on the real location
    # targeted by these memory address, and thus there is no guarantee that the result of the analysis is correct.
    detect_memory_writes_to_tainted_address(initial_program_state)
    # As angr is a symbolic executor, by default it adds state constraints whenever a conditional branch is encountered with
    # symbolic value used as a condition. As we are not actually performing a symbolic execution we don't want these
    # constraints added.
    do_not_add_constraints_for_tainted_branches(initial_program_state)
    # These above actions on the initial program state will be inherited by the successor program states generated by angr.

    # The basic blocks discovered, keyed by their ID.
    discovered_blocks: dict[tuple, BasicBlock] = {}
    # States from which an exploration should be performed. This is the list of remaining jobs to do.
    states_to_process: set[angr.SimState] = set()

    # Add the initial program state in `discovered_blocks` and `states_to_process`.
    incorporate_state_into_cfg(
        discovered_blocks=discovered_blocks,
        states_to_process=states_to_process,
        new_state=initial_program_state,
        block_consolidation_threshold=block_consolidation_threshold,
    )

    nb_it = 0

    signal.alarm(CommonConfig().timeout)

    try:
        # This is the main analysis loop. When there is no state to process anymore, the fixed-point is reached and we exit the loop.
        pbar = tqdm(
            desc="Exploring states...", disable=CommonConfig().progress_bars_disabled
        )
        process = psutil.Process()
        while states_to_process:
            # Pick a state from the pool of states to be processed
            current_state = states_to_process.pop()

            # Propagate the tainting state from the program state and obtain its successor program states. As the simulated
            # execution of the state is performed by angr, memory/register bytes whose value depends on tainted or multivalued
            # data will receive appropriate symbolic expressions.
            successor_states = current_state.step()

            # Make sure that no successor has inherited the tainting state cache from the previous angr states
            for successor in successor_states:
                assert not hasattr(successor.registers, "cached_tainting_state")
                assert not hasattr(successor.memory, "cached_tainting_state")

            # Incorporate each successor in the collection of already discovered blocks
            for successor_state in successor_states:
                # This updates `discovered_blocks` and `states_to_process`
                incorporate_state_into_cfg(
                    discovered_blocks=discovered_blocks,
                    states_to_process=states_to_process,
                    new_state=successor_state,
                    block_consolidation_threshold=block_consolidation_threshold,
                )
            pbar.update()
            nb_it += 1
            if nb_it % 100 == 0:
                mem_mb = process.memory_info().rss / (
                    1024 * 1024
                )  # Resident Set Size in MB
                logger.info(
                    f"Memory usage {mem_mb:.2f}mb",
                    extra={"it_no": nb_it, "mem_usage_mb": f"{mem_mb:.2f}"},
                )
                logger.info(
                    f"successor_states length : {len(states_to_process)}",
                    extra={
                        "it_no": nb_it,
                        "successor_states_len": len(states_to_process),
                    },
                )
                logger.info(
                    f"Nb discovered blocks : {len(discovered_blocks)}",
                    extra={"it_no": nb_it, "nb_blocks": len(discovered_blocks)},
                )
                logger.info(
                    "Nb sates",
                    extra={
                        "it_no": nb_it,
                        "nb_states": sum([len(b) for b in discovered_blocks]),
                    },
                )

        pbar.close()
    except KeyboardInterrupt as e:
        logger.error("Keyboard interrupt")
        logger.info(e)
        raise AnalysisInterruptError(
            dicovered_blocks=discovered_blocks,
            kind=AnalysisInterruptKind.KeyboardInterrupt,
        )
    except TaintedAddressMemoryWrite as e:
        logger.info(e)
        raise AnalysisInterruptError(
            dicovered_blocks=discovered_blocks,
            kind=AnalysisInterruptKind.TaintedMemoryWrite,
        )
    except Timeout:
        logger.warning("Timeout interrupt")
        raise AnalysisInterruptError(
            dicovered_blocks=discovered_blocks,
            kind=AnalysisInterruptKind.Timeout,
        )
    finally:
        logger.info("Iteration count final", extra={"nb_it": nb_it})
        logger.info(
            "Nb discovered blocks final",
            extra={"it_no": nb_it, "nb_blocks": len(discovered_blocks)},
        )
        logger.info(
            "Nb sates final",
            extra={
                "it_no": nb_it,
                "nb_states": sum([len(b) for b in discovered_blocks]),
            },
        )

    return discovered_blocks


def incorporate_state_into_cfg(
    discovered_blocks: dict[tuple, BasicBlock],
    states_to_process: set[angr.SimState],
    new_state: angr.SimState,
    block_consolidation_threshold: int,
) -> None:
    """
    Incorporates a new angr state into the collection of discovered blocks, and updates the list of states to explore.

    This function adds `new_state` into `discovered_blocks`. If a block for `new_state` is already present in `discovered_blocks`,
    `new_state` is incorporated into the existing block, which may trigger the consolidation of the block. Otherwise,
    a new block is created.

    If incorporating `new_state` did change `discovered_blocks`, an exploration from the new state (which can be
    either `new_state` or a consolidated state) is requested by adding it to `states_to_process`.
    """
    block_id = get_block_id(new_state)

    if block_id in discovered_blocks:
        old_block = discovered_blocks[block_id]
        new_block = incorporate_state_into_block(
            new_state, old_block, block_consolidation_threshold
        )
        discovered_blocks[block_id] = new_block

        match old_block, new_block:
            case ConsolidatedBasicBlock(
                state=old_consolidated_state
            ), ConsolidatedBasicBlock(state=new_consolidated_state):
                if tainting_state_at_angr_program_state(
                    old_consolidated_state
                ) != tainting_state_at_angr_program_state(new_consolidated_state):
                    states_to_process.add(new_consolidated_state)

            case MultiStatesBasicBlock(), ConsolidatedBasicBlock(
                state=new_consolidated_state
            ):
                states_to_process.add(new_consolidated_state)

            case MultiStatesBasicBlock(), MultiStatesBasicBlock():
                states_to_process.add(new_state)

    else:
        discovered_blocks[block_id] = MultiStatesBasicBlock(states=[new_state])
        states_to_process.add(new_state)


def incorporate_state_into_block(
    state: angr.SimState, old_block: BasicBlock, block_consolidation_threshold: int
) -> BasicBlock:
    """
    Builds a new basic bloc representing the result of adding a program state to an existing block.
    """
    match old_block:
        case MultiStatesBasicBlock(states=old_states):
            new_states = old_states + [state]
            if len(new_states) < block_consolidation_threshold:
                return MultiStatesBasicBlock(states=new_states)
            else:
                consolidated_state = merge_program_states(new_states)
                logger.debug(f"Block consolidated at PC {hex(state.ip.concrete_value)}")  # type: ignore
                return ConsolidatedBasicBlock(state=consolidated_state)

        case ConsolidatedBasicBlock(state=old_consolidated_state):
            new_consolidated_state = merge_program_states(
                [old_consolidated_state, state]
            )
            if old_consolidated_state != new_consolidated_state:
                logger.debug(
                    f"Consolidated block updated at PC {hex(state.ip.concrete_value)}"  # type: ignore
                )
            return ConsolidatedBasicBlock(state=new_consolidated_state)

        case _:
            assert False


def tainting_state_at_angr_program_state(program_state: angr.SimState) -> dict:
    """
    Computes the tainting state of an angr program state.

    An angr program state stores the content of the registers and memory, which is a mix of concrete and symbolic data. In our
    analysis, we use symbolic data to represent the red tainted bytes, orange tainted bytes, and green tainted bytes.

    A tainting state describes the status of each byte in the registers and memory. It is a mapping from byte addresses to either
    'red', 'orange', 'green', or a concrete value.

    This function returns two tainting states, one for the bytes of the registers and the other for the bytes of the memory.
    """
    return {
        "registers": tainting_state_in_area(program_state.registers),
        "memory": tainting_state_in_area(program_state.memory),
    }


def tainting_state_in_area(memory: DefaultMemory, use_cache: bool = True) -> dict:
    """
    Computes the tainting state of an angr `DefaultMemory` object.

    Angr uses one instance of `DefaultMemory` to represent the state of the memory, and another instance of `DefaultMemory` to
    represent the state of the registers. An instance of `DefaultMemory` contains a mix of concrete and symbolic values. In our
    analysis, we use symbolic data to represent the red tainted bytes, orange tainted bytes, and green tainted bytes.

    A tainting state describes the status of each byte in the registers and memory. It is a mapping from byte addresses to either
    'red', 'orange', 'green', or a concrete value.

    To save computation, the computed tainting state is stored into an attribute of `memory`, such that subsequent calls to
    the present function with the same `memory` instance return the cached tainting state instead of recomputing it. Care must
    be taken to remove / update this cache attribute when `memory` is modified.
    """

    if use_cache and hasattr(memory, "cached_tainting_state"):
        return memory.cached_tainting_state  # type: ignore

    result = {}
    # Unfortunately, using the `load` method for each byte of `memory` is too slow, and thus we have no choice but to dig into
    # the internal attributes of `memory` to extract the information we need.

    # Internally, the content of a `DefaultMemory` instance is stored in a collection of pages
    for page_index, page in memory._pages.items():
        # The symbolic and the concrete content of a page are stored in different locations
        # page.symbolic_data is a dict of symbolic expressions stored in the page, keyed by address. Each symbolic expression
        # can correspond to data that spans several bytes in the page.
        for symbolic_object in page.symbolic_data.values():  # type: ignore
            for tainted_address in range(
                symbolic_object.base, symbolic_object.base + symbolic_object.length
            ):
                # we use memory.load to automatically build symbolic expressions for a single byte.
                # memory.load is slow but this is ok as most of the memory content is not symbolic.
                symbolic_expression = memory.load(tainted_address, 1)
                # logger.debug(f"symbolic_expression_len : {symbolic_expression.length}")
                tainting_state = status_from_expression(
                    symbolic_expression, memory.state
                )
                result[tainted_address] = tainting_state
        # page.symbolic_bitmap is a list with the same length as the page, where each entry of the list is 0 if the
        # corresponding page byte is concrete, or 1 if it is symbolic. Note that it seems that 1 is also used for uninitialized
        # data.
        for byte_index, byte_status in enumerate(page.symbolic_bitmap):  # type: ignore
            if byte_status == 0:
                # page.concrete_data contains the values of the concrete bytes of the page
                tainting_state = status_from_expression(
                    page.concrete_data[byte_index],  # type: ignore
                    memory.state,
                )
                result[page_index * memory.page_size + byte_index] = tainting_state
    memory.cached_tainting_state = result  # type: ignore
    return result


def merge_tainting_states(tainting_state1: dict, tainting_state2: dict) -> dict:
    """
    From two tainting states, computes a new over approximated tainting state.

    A tainting state describes the status of each byte in the registers and memory. It is a mapping from byte addresses to either
    'red', 'orange', 'green', or a concrete value.
    """

    # A tainting state is a dict containing one entry for the registers and one entry for the memory. Each entry is itself a
    # dict of byte addresses and statuses.
    assert set(tainting_state1) == {"registers", "memory"}
    assert set(tainting_state2) == {"registers", "memory"}

    result = {}

    for area in ["registers", "memory"]:
        area_result = {}
        result[area] = area_result
        area_tainting_state1 = tainting_state1[area]
        area_tainting_state2 = tainting_state2[area]
        # Some bytes may appear only in one tainting state, if they are uninitialized data in the other tainting state.
        addresses = set(area_tainting_state1.keys()) | set(area_tainting_state2.keys())
        for address in addresses:
            area_result[address] = get_over_approximation_of_statuses(
                area_tainting_state1.get(address), area_tainting_state2.get(address)
            )

    return result


def merge_program_states(program_states: list[angr.SimState]) -> angr.SimState:
    """
    Merges program states, by computing a new program state that over approximates the tainting states of the given program states.
    """
    pb_disable = CommonConfig().progress_bars_disabled
    if (
        len(program_states)
        >= TargetConfigManager().get_config().min_consolidation_threshold
    ):
        pb_disable = True
    tainting_states = [
        tainting_state_at_angr_program_state(program_state)
        for program_state in tqdm(
            program_states,
            desc="Computing tainting states...",
            leave=False,
            disable=pb_disable,
        )
    ]
    progress_iter = tqdm(
        tainting_states, desc="Merging states...", leave=False, disable=pb_disable
    )
    target_tainting_state = functools.reduce(
        merge_tainting_states, progress_iter, tainting_states[0]
    )

    # The goal now is to obtain an angr program state whose memory and register content corresponds to `target_tainting_state`.
    # For simplicity, instead of building a new angr program state from scratch, we take one of the existing angr program
    # states and we modify the memory and register bytes appropriately.
    result_program_state = program_states[0].copy()
    make_memory_match_tainting_state(
        result_program_state.registers, target_tainting_state["registers"]
    )
    make_memory_match_tainting_state(
        result_program_state.memory, target_tainting_state["memory"]
    )

    return result_program_state


def make_memory_match_tainting_state(
    memory: angr.storage.memory_mixins.DefaultMemory,  # type: ignore
    target_tainting_state: dict,
) -> None:
    """
    Modifies an angr `DefaultMemory` instance such that its content matches a desired tainting state.

    Angr uses `DefaultMemory` instances to store the content of the registers and the memory of a program state. A `DefaultMemory`
    instance stores a mix of concrete and symbolic data. In our analysis, we use the symbolic data to represent red tainted bytes,
    orange tainted bytes, and green tainted bytes.

    This function modifies the bytes stored in `memory` such that their value corresponds to the status described in
    `target_tainting_state`. `target_tainting_state` is a mapping from byte addresses to either 'red', 'orange', 'green' or a
    concrete value.
    """
    current_tainting_state = tainting_state_in_area(memory)

    for address in target_tainting_state:
        # `target_tainting_state` may include bytes that are uninitialized in `memory`.
        try:
            current_status = current_tainting_state[address]
        except KeyError:
            current_status = None
        target_status = target_tainting_state[address]

        if current_status != target_status:
            expression = build_expression_for_status(target_status, 1)
            memory.store(address, expression)

    # as `memory` was updated, we need to update its cached tainting state as well
    memory.cached_tainting_state = target_tainting_state


# In the functions below, we use a nice feature of angr which allows to register callback functions for various execution
# events. Such a callback is executed when the requested event happens and receives as argument the current program state, which
# allows to check and to modify it.
def contaminate_tainted_memory_reads_with_taint(
    program_state: angr.SimState,
) -> None:
    """
    Modifies an angr program state such that memory reads with a tainted address produce tainted data.

    If the address is red, the result of the read is some red tainted data. Otherwise, the result of the read is some orange
    tainted data.
    """

    def after_memory_read_hook(program_state: angr.SimState):
        """
        If the memory read which was just performed has a tainted address, make it result in a tainted value.

        This is a callback function executed after each memory read encountered during the execution.
        """
        read_address_status = status_from_expression(
            program_state.inspect.mem_read_address,  # type: ignore
            program_state,
        )
        try:
            match read_address_status:
                case Color.Red:
                    expression = build_expression_for_status(
                        Color.Red,
                        size_bytes=program_state.inspect.mem_read_length,  # type: ignore
                    )
                    program_state.inspect.mem_read_expr = expression  # type: ignore
                case Color.Orange | Color.Green:
                    expression = build_expression_for_status(
                        Color.Orange,
                        size_bytes=program_state.inspect.mem_read_length,  # type: ignore
                    )
                    program_state.inspect.mem_read_expr = expression  # type: ignore
        except Exception:
            logger.error("An error occured.")
            logger.debug(
                f"{read_address_status}, {type(read_address_status)}, {program_state.inspect.mem_read_address}"  # type: ignore
            )
            raise

    program_state.inspect.b(
        "mem_read", when=angr.BP_AFTER, action=after_memory_read_hook
    )


def detect_memory_writes_to_tainted_address(program_state: angr.SimState) -> None:
    """
    Modifies an angr program state such that memory writes to a tainted address raise an exception.

    If a memory write with a tainted address is encountered, there is no constraint about what the target address of
    the write is, and thus there is no guarantee that the result of the analysis is correct.
    """

    def before_memory_write_hook(state: angr.SimState):
        """
        If the memory write that is about to be performed has a tainted address, raise an exception.

        This is a callback function executed before each memory write encountered during the execution.
        """
        write_address_status = status_from_expression(
            state.inspect.mem_write_address,  # type: ignore
            state,
        )
        # if write_address_status in ["red", "orange", "green"]:
        if isinstance(write_address_status, Color):
            logger.debug(
                f"Memory write to tainted address {state.inspect.mem_write_address} at {state.addr}"  # type: ignore
            )
            sources_dirs = TargetConfigManager().get_config().source_code_dirs
            bin_f_n: str = state.project.filename  # type: ignore
            src_l = SourceCodeFilesManager().get_source_lines(
                bin_f_n, pc_offset(state), sources_dirs
            )
            logger.debug(src_l)
            logger.debug(hex(pc_offset(state)))
            logger.debug(hex(state.addr))
            logger.debug(f"State's block: \n{state.block().disassembly}")
            raise TaintedAddressMemoryWrite

    program_state.inspect.b(
        "mem_write", when=angr.BP_BEFORE, action=before_memory_write_hook
    )
    # program_state.inspect.b('reg_write', when=angr.BP_BEFORE, action=before_memory_write_hook)


def do_not_add_constraints_for_tainted_branches(program_state: angr.SimState) -> None:
    """
    Modifies an angr program state such that no state constraint is added when branching with a tainted condition is encountered.
    """

    def before_add_constraints_hook(state):
        added_constraints = state.inspect.added_constraints
        for constraint in added_constraints:
            if isinstance(status_from_expression(constraint, state), Color):
                state.inspect.added_constraints = []

            # if status_from_expression(constraint, state) in [
            #     "red",
            #     "orange",
            #     "green",
            # ]:
            #     state.inspect.added_constraints = []

    program_state.inspect.b(
        "constraints", when=angr.BP_BEFORE, action=before_add_constraints_hook
    )


def get_block_id(block: angr.SimState) -> tuple[*tuple[int, ...], int]:
    """
    Computes the unique ID of a basic block.

    The ID of a block is determined by the program address of the first instruction of the block, and by the addresses of the
    sequence of call instructions that led to the execution of the function this block belongs to. As a consequence,
    if a function is called from several locations of the target program, a separate analysis of the function will be performed
    for each possible calling site.
    """
    call_sites = [callstack.call_site_addr for callstack in block.callstack]
    # todo : still necessary ?
    # try:
    #     addr: int = block.addr
    # except:
    #     print("Basic Block ID Error")
    #     print(f"IP value : {block.ip}")
    #     cs = [hex(s) for s in call_sites]
    #     print(f"Call sites : {cs}")
    #     print(type(block.ip))

    #     # print(block.block())

    #     raise Exception
    addr: int = block.addr
    return *call_sites, addr
