min_consolidation_threshold: 20000
max_consolidation_threshold: 50000
source_code_dirs:
  - tests/cases
  - bench-libs
hooks:
  plugin: ya_cttool.plugins.hydrogen
  symbol_names:
    - hydro_random_ensure_initialized