app_config:
  min_consolidation_threshold: 20000
  max_consolidation_threshold: 50000
  source_code_dirs:
    - tests/cases
    - bench-libs
  hooks:
    plugin: ""
    symbol_names: []
test_config:
  cases_bin_dir: tests/build/tmp
  cases_src_dir: tests/cases
  results_dir: results
  cases_expected_dir: tests/cases/_expected
  cases_bin:
    - br-aes_ct_cbcenc
  compiler_info_file: compiler_info.txt
  compiler: gcc
  fail: false
  test_mode: True
  save_explored_states: False
